### ISSUE TITLE
Count of cases and controls not as expected

### ISSUE THREAD

**Issue by laurapyle** [PheWAS/PheWAS#56]
Hello,

I am using the PheWAS package to compare phenotypes in people with and without sex chromosome aneuploidies. I used the createPhewasTable function to reshape the data into wide format, with one record per person (N=1310). However, when I run the phewas itself, the count of cases and controls is much higher than expected (e.g., ~13,000 controls and ~1200 cases.  I have worked through the vignette and read the documentation and am not sure what I am doing wrong.

Any advice would be greatly appreciated!

Thank you,
Laura

**Comment by RobertJCarroll** [comment]
I don't have much to go on with what you've shared. Having said that, it sounds like you are encountering a join issue- ie, there are some duplications of IDs in different tables that are causing multiple rows per individual. 

If I were you, I would merge your predictors, outcomes, and covariates first so that you can check the size of the data frame, then use `phewas_ext()` which may provide some more details.

**Comment by laurapyle** [comment]
I know I didn't give you much to go on but this helped me pinpoint the problem.  Thanks so much!
